# Generated by Django 4.2.5 on 2023-09-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
